# -*- coding: utf-8 -*-
"""auto_label

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLhF8stG3zJE_gVpw4do_RUoLdAqkKzU

auto_label.py
SAES(Scenario-Adaptive Engagement Score) 자동 라벨링 파이프라인.
수동 주석 없이 순수 시선 좌표 신호로 인지적 몰입도 pseudo GT를 생성한다.
Scenarios: paper reading / code debugging / online lecture
"""

# ==============================================================================
# 🎯 통합 자동 라벨링 — paper / coding / lecture 공통 구조
# ==============================================================================
#
# [설계 원칙]
#
#   1. GT는 engagement와 독립적인 신호로 정의
#      - engagement: section_score, scroll 등 콘텐츠 맥락 신호 포함
#      - GT:         순수 시선 좌표 신호만 사용 (gaze_x, gaze_y 기반)
#        → 두 값이 상관은 있되 순환 정의가 되지 않도록 분리
#
#   2. 세 시나리오가 동일한 feat_ 집합 사용, 가중치만 다르게
#      → LOO-CV에서 시나리오 혼재 시 일관된 집중도 개념 학습 가능
#
#   3. GT 공식
#      paper  : 0.50*(1-disp) + 0.30*hc         + 0.20*(1-back)
#      coding : 0.45*(1-disp) + 0.30*(1-back)    + 0.25*mouse_speed  (마우스 있음)
#               0.50*(1-disp) + 0.30*hc          + 0.20*(1-back)     (마우스 없음)
#      lecture: 0.50*(1-disp) + 0.30*video_ratio + 0.20*(1-back)
#               0.50*(1-disp) + 0.30*stability   + 0.20*(1-back)     (video 없음)
#
#      → engagement와 겹치는 section_score, scroll_regularity, sec 제거
#      → 순수 시선 좌표 파생 신호만 GT에 사용
#
#   4. 피험자 내 sigmoid 정규화로 분산 확보
#      → GT std 0.20 이상 보장
#      → LOO-CV 이전에 시나리오별 minmax 정규화 별도 적용

# ==============================================================================
# 0. 라이브러리
# ==============================================================================
from google.colab import drive
import os
import pandas as pd
import numpy as np
from scipy.ndimage import uniform_filter1d

drive.mount('/content/drive', force_remount=True)
print("✅ 드라이브 마운트 완료")

# ==============================================================================
# 피험자별 파일 경로 설정
# ==============================================================================
# ⚠️ 실제 경로로 수정하세요
BASE_RAW = '/content/drive/MyDrive/livinglab_2/data/gaze_output'
BASE_OUT = '/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과'

SUBJECT_FILES = {
    # scenario: [(subject, input_path, output_path), ...]
    'paper': [
        ('jisu',   f'{BASE_RAW}/autogaze_labeled_jisu2_completed4.csv',
                   f'{BASE_OUT}/autogaze_paper_jisu.csv'),
        ('namwoo', f'{BASE_RAW}/gaze_maui_final_namwoo4.csv',
                   f'{BASE_OUT}/autogaze_paper_namwoo.csv'),
        ('yoonjo', f'{BASE_RAW}/gaze_maui_final_yoonjo2.csv',
                   f'{BASE_OUT}/autogaze_paper_yoonjo.csv'),
    ],
    'coding': [
        ('namwoo', f'{BASE_RAW}/gaze_maui_final_coding_namwoo.csv',
                   f'{BASE_OUT}/autogaze_coding_namwoo.csv'),
        ('yoonjo', f'{BASE_RAW}/gaze_maui_final_coding_yoonjo.csv',
                   f'{BASE_OUT}/autogaze_coding_yoonjo.csv'),
    ],
    'lecture': [
        ('namwoo', f'{BASE_RAW}/gaze_maui_final_online_namwoo.csv',
                   f'{BASE_OUT}/autogaze_lecture_namwoo.csv'),
        ('yoonjo', f'{BASE_RAW}/gaze_maui_final_online_yoonjo.csv',
                   f'{BASE_OUT}/autogaze_lecture_yoonjo.csv'),
    ],
}

# 섹션 분류
VIDEO_SECTIONS   = ['media', 'video-player', 'video', 'player', 'lecture-video']
NOTE_SECTIONS    = ['note', 'note/editor', 'slides', 'pdf',
                    'article', 'content-list', 'content-grid']
OUTSIDE_SECTIONS = ['outside', 'unknown']


# ==============================================================================
# 공통 유틸
# ==============================================================================

def _normalize(series: pd.Series) -> pd.Series:
    mn, mx = series.min(), series.max()
    if mx - mn < 1e-9:
        return pd.Series(np.zeros(len(series)), index=series.index)
    return (series - mn) / (mx - mn)


def _sigmoid_normalize(arr: np.ndarray, scale: float = 6.0) -> np.ndarray:
    """
    Sigmoid 정규화.
    극단값 압축 + 중간 구간 확보 → 단봉 분포 유도.
    engagement와 GT가 같은 feat_를 쓰더라도
    비선형 변환으로 분포 형태가 달라져 독립성 부분 확보.
    """
    center      = np.median(arr)
    transformed = 1.0 / (1.0 + np.exp(-scale * (arr - center)))
    mn, mx      = transformed.min(), transformed.max()
    if mx - mn < 1e-6:
        return arr.copy()
    return (transformed - mn) / (mx - mn)


def smooth_and_normalize(df, cols, smooth_sec=2.0):
    dt = df['timestamp_sec'].diff().median()
    if pd.isna(dt) or dt <= 0:
        dt = 0.033
    win = max(1, int(smooth_sec / dt))
    for col in cols:
        df[col] = uniform_filter1d(df[col].values.astype(float), size=win)
        df[col] = _normalize(df[col])
    return df


def discretize(df, cols, thresholds=None):
    default_thr = {
        'engagement': (0.35, 0.65),
        'confusion':  (0.30, 0.60),
        'fatigue':    (0.30, 0.60),
    }
    thr = {**default_thr, **(thresholds or {})}
    for col in cols:
        lo, hi = thr.get(col, (0.33, 0.67))
        df[f'{col}_label'] = np.where(
            df[col] < lo, 0, np.where(df[col] < hi, 1, 2)
        )
    return df


# ==============================================================================
# STEP 1. 공통 Feature 추출
# ==============================================================================

def extract_gaze_features(df: pd.DataFrame,
                           scenario: str,
                           window_sec: float = 3.0) -> pd.DataFrame:
    """
    세 시나리오 공통 feature 추출.
    시나리오별 추가 feature는 별도 섹션에서 계산.
    """
    df  = df.copy().sort_values('timestamp_sec').reset_index(drop=True)
    dt  = df['timestamp_sec'].diff().median()
    win = max(1, int(window_sec / dt)) if dt and dt > 0 else 30

    dx = df['gaze_x'].diff()
    dy = df['gaze_y'].diff()

    # ── 공통: 수평 이동 ───────────────────────────────────────────────────
    move_right = (dx > 0).astype(float)
    move_left  = (dx < 0).astype(float)
    df['feat_horizontal_consistency'] = (
        move_right.rolling(win, min_periods=1).mean()
        - move_left.rolling(win, min_periods=1).mean()
    )
    df['feat_backtrack_ratio'] = move_left.rolling(win, min_periods=1).mean()

    # ── 공통: 시선 분산 ───────────────────────────────────────────────────
    sx = df['gaze_x'].rolling(win, min_periods=1).std().fillna(0)
    sy = df['gaze_y'].rolling(win, min_periods=1).std().fillna(0)
    df['feat_gaze_dispersion'] = np.sqrt(sx**2 + sy**2)

    # 강의: 분산 역수 = 안정성
    df['feat_gaze_stability'] = 1.0 / (df['feat_gaze_dispersion'] + 1.0)

    # ── 공통: 안구 도약 속도 ──────────────────────────────────────────────
    speed = np.sqrt(dx**2 + dy**2) / df['timestamp_sec'].diff().replace(0, np.nan)
    df['feat_saccade_velocity_mean'] = speed.rolling(win, min_periods=1).mean().fillna(0)

    # ── 공통: 고정(fixation) ──────────────────────────────────────────────
    threshold = 20
    if all(c in df.columns for c in ['screen_x_px', 'screen_y_px']):
        pixel_dist  = np.sqrt(
            df['screen_x_px'].diff()**2 + df['screen_y_px'].diff()**2
        ).fillna(0)
        is_fixation = (pixel_dist < threshold).astype(float)
        df['feat_fixation_duration_mean'] = (
            (is_fixation * dt).rolling(win, min_periods=1).sum()
            / is_fixation.rolling(win, min_periods=1).sum().replace(0, np.nan)
        ).fillna(0)
    else:
        df['feat_fixation_duration_mean'] = 0.0

    # ── 공통: Iris 움직임 ─────────────────────────────────────────────────
    if all(c in df.columns for c in ['iris_L_x_px','iris_L_y_px','iris_R_x_px','iris_R_y_px']):
        iris_dx = (df['iris_R_x_px'] - df['iris_L_x_px']).diff().abs()
        iris_dy = (df['iris_R_y_px'] - df['iris_L_y_px']).diff().abs()
        df['feat_iris_movement'] = (iris_dx + iris_dy).rolling(win, min_periods=1).mean().fillna(0)
    else:
        df['feat_iris_movement'] = 0.0

    # ── 공통: 섹션 스코어 ─────────────────────────────────────────────────
    df['feat_section_score_mean'] = (
        df.get('gaze_section_score', pd.Series(0.5, index=df.index))
        .rolling(win, min_periods=1).mean().fillna(0)
    )
    df['feat_top_seg_score_mean'] = (
        df.get('seg1_score', pd.Series(0.5, index=df.index))
        .rolling(win, min_periods=1).mean().fillna(0)
    )

    # ── 공통: 섹션 일관성 & 재방문율 ─────────────────────────────────────
    gaze_sec     = df.get('gaze_section', pd.Series('', index=df.index))
    same_section = (gaze_sec == gaze_sec.shift(1)).astype(float)
    df['feat_section_consistency'] = same_section.rolling(win, min_periods=1).mean()

    def revisit_rate(series, w):
        rates = []
        for i in range(len(series)):
            start  = max(0, i - w + 1)
            window = series.iloc[start:i+1]
            if len(window) < 2:
                rates.append(0.0); continue
            seen, revisit = set(), 0
            for v in window:
                if v in seen: revisit += 1
                seen.add(v)
            rates.append(revisit / (len(window) - 1))
        return pd.Series(rates, index=series.index)

    df['feat_revisit_rate'] = revisit_rate(gaze_sec.fillna(''), win)

    # ── 시나리오별 추가 feature ───────────────────────────────────────────

    if scenario == 'paper':
        if 'scrollY' in df.columns:
            scroll_diff       = df['scrollY'].diff().fillna(0)
            scroll_down_ratio = (scroll_diff > 0).astype(float).rolling(win, min_periods=1).mean()
            scroll_std        = scroll_diff.rolling(win, min_periods=1).std().fillna(0)
            max_std           = scroll_std.max() if scroll_std.max() > 0 else 1.0
            df['feat_scroll_regularity'] = (
                scroll_down_ratio * 0.5 + (1.0 - scroll_std / max_std) * 0.5
            )
        else:
            df['feat_scroll_regularity'] = 0.5

        # outside 비율
        if 'gaze_section' in df.columns:
            df['feat_outside_ratio'] = (
                df['gaze_section'].isin(OUTSIDE_SECTIONS).astype(float)
                .rolling(win, min_periods=1).mean()
            )
        else:
            df['feat_outside_ratio'] = 0.0

    elif scenario == 'coding':
        # 마우스 신호
        has_mouse = ('mouse_x' in df.columns) and ('mouse_y' in df.columns)
        if has_mouse:
            dt_series = df['timestamp_sec'].diff().replace(0, np.nan)
            mdx       = df['mouse_x'].diff()
            mdy       = df['mouse_y'].diff()
            dist      = np.sqrt(mdx**2 + mdy**2).fillna(0)
            df['feat_mouse_speed_mean']    = (dist / dt_series).fillna(0).rolling(win, min_periods=1).mean()
            df['feat_mouse_travel_sum']    = dist.rolling(win, min_periods=1).sum()
            if all(c in df.columns for c in ['screen_x_px', 'screen_y_px']):
                df['feat_gaze_mouse_gap_mean'] = np.sqrt(
                    (df['screen_x_px'] - df['mouse_x'])**2 +
                    (df['screen_y_px'] - df['mouse_y'])**2
                ).fillna(0).rolling(win, min_periods=1).mean()
            else:
                df['feat_gaze_mouse_gap_mean'] = 0.0
        else:
            df['feat_mouse_speed_mean']    = 0.0
            df['feat_mouse_travel_sum']    = 0.0
            df['feat_gaze_mouse_gap_mean'] = 0.0

        if 'gaze_section' in df.columns:
            df['feat_outside_ratio'] = (
                df['gaze_section'].isin(OUTSIDE_SECTIONS).astype(float)
                .rolling(win, min_periods=1).mean()
            )
        else:
            df['feat_outside_ratio'] = 0.0

    elif scenario == 'lecture':
        if 'gaze_section' in df.columns:
            is_video   = df['gaze_section'].isin(VIDEO_SECTIONS).astype(float)
            is_outside = df['gaze_section'].isin(OUTSIDE_SECTIONS).astype(float)
            df['feat_video_watch_ratio'] = is_video.rolling(win, min_periods=1).mean()
            df['feat_outside_ratio']     = is_outside.rolling(win, min_periods=1).mean()
            df['feat_video_miss_ratio']  = 1.0 - df['feat_video_watch_ratio']

            prev_sec  = gaze_sec.shift(1)
            is_switch = (
                (gaze_sec != prev_sec) &
                (gaze_sec.isin(NOTE_SECTIONS) | gaze_sec.isin(VIDEO_SECTIONS))
            ).astype(float)
            df['feat_note_switch']      = is_switch.rolling(win, min_periods=1).mean()
            section_change              = (gaze_sec != prev_sec).astype(float)
            df['feat_periodic_pattern'] = section_change.rolling(win * 2, min_periods=1).mean()
        else:
            df['feat_video_watch_ratio'] = 0.5
            df['feat_outside_ratio']     = 0.5
            df['feat_video_miss_ratio']  = 0.5
            df['feat_note_switch']       = 0.0
            df['feat_periodic_pattern']  = 0.0

    return df


# ==============================================================================
# STEP 2. Engagement / Confusion / Fatigue (시나리오별)
# ==============================================================================

def compute_states(df: pd.DataFrame, scenario: str):
    """engagement / confusion / fatigue 계산."""

    if scenario == 'paper':
        hc     = _normalize(df['feat_horizontal_consistency'])
        disp   = _normalize(df['feat_gaze_dispersion'])
        sec    = _normalize(df['feat_section_score_mean'])
        scroll = _normalize(df['feat_scroll_regularity'])
        back   = _normalize(df['feat_backtrack_ratio'])
        rev    = _normalize(df['feat_revisit_rate'])
        fix    = _normalize(df['feat_fixation_duration_mean'])
        iris   = _normalize(df['feat_iris_movement'])
        vel    = _normalize(df['feat_saccade_velocity_mean'])
        t_col  = 't_rel' if 't_rel' in df.columns else 'timestamp_sec'
        time   = _normalize(df[t_col])

        eng = (0.35*hc + 0.25*(1-disp) + 0.25*sec + 0.10*scroll + 0.05*(1-back)).clip(0,1)
        con = (0.35*back + 0.25*disp + 0.20*rev + 0.20*(1-sec)).clip(0,1)
        fat = (0.35*fix + 0.25*(1-iris) + 0.20*(1-vel) + 0.20*time).clip(0,1)

    elif scenario == 'coding':
        disp  = _normalize(df['feat_gaze_dispersion'])
        sec   = _normalize(df['feat_section_score_mean'])
        back  = _normalize(df['feat_backtrack_ratio'])
        ms    = _normalize(df['feat_mouse_speed_mean'])
        gap   = _normalize(df['feat_gaze_mouse_gap_mean'])
        hc    = _normalize(df['feat_horizontal_consistency'])
        travel= _normalize(df['feat_mouse_travel_sum'])
        fix   = _normalize(df['feat_fixation_duration_mean'])
        iris  = _normalize(df['feat_iris_movement'])
        vel   = _normalize(df['feat_saccade_velocity_mean'])
        t_col = 't_rel' if 't_rel' in df.columns else 'timestamp_sec'
        time  = _normalize(df[t_col])

        has_mouse = df['feat_mouse_speed_mean'].sum() > 0
        if has_mouse:
            eng = (0.30*(1-disp) + 0.20*(1-back) + 0.15*sec + 0.15*ms + 0.12*(1-gap) + 0.08*hc).clip(0,1)
            con = (0.30*back + 0.25*travel + 0.20*disp + 0.15*gap + 0.10*sec).clip(0,1)
            fat = (0.30*fix + 0.25*(1-ms) + 0.20*(1-iris) + 0.15*(1-vel) + 0.10*time).clip(0,1)
        else:
            eng = (0.35*(1-disp) + 0.30*(1-back) + 0.20*sec + 0.15*hc).clip(0,1)
            con = (0.40*back + 0.35*disp + 0.25*sec).clip(0,1)
            fat = (0.35*fix + 0.30*(1-iris) + 0.20*(1-vel) + 0.15*time).clip(0,1)

    elif scenario == 'lecture':
        video  = _normalize(df['feat_video_watch_ratio'])
        stab   = _normalize(df['feat_gaze_stability'])
        sec    = _normalize(df['feat_section_score_mean'])
        switch = _normalize(df['feat_note_switch'])
        rev    = _normalize(df['feat_revisit_rate'])
        back   = _normalize(df['feat_backtrack_ratio'])
        disp   = _normalize(df['feat_gaze_dispersion'])
        miss   = _normalize(df['feat_video_miss_ratio'])
        outside= _normalize(df['feat_outside_ratio'])
        fix    = _normalize(df['feat_fixation_duration_mean'])
        iris   = _normalize(df['feat_iris_movement'])
        vel    = _normalize(df['feat_saccade_velocity_mean'])
        t_col  = 't_rel' if 't_rel' in df.columns else 'timestamp_sec'
        time   = _normalize(df[t_col])
        period = _normalize(df['feat_periodic_pattern'])

        optimal_switch = 1.0 - 2.0 * (switch - 0.5).abs()
        eng = (0.30*video + 0.25*stab + 0.20*sec + 0.15*optimal_switch + 0.05*(1-rev) + 0.05*(1-back)).clip(0,1)
        con = (0.25*back + 0.25*disp + 0.20*miss + 0.20*outside + 0.05*(1-sec) + 0.05*rev).clip(0,1)
        fat = (0.30*fix + 0.25*(1-iris) + 0.20*(1-vel) + 0.15*time + 0.10*(1-period)).clip(0,1)

    return eng, con, fat


# ==============================================================================
# STEP 3. objective_gt — engagement와 독립적인 순수 시선 신호
# ==============================================================================

def compute_objective_gt(df: pd.DataFrame, scenario: str) -> np.ndarray:
    """
    [핵심 설계]
    GT = 순수 시선 좌표 파생 신호만 사용
         → engagement에 포함된 section_score, scroll_regularity 제외
         → 피험자/시나리오 무관하게 동일한 "집중 시선 패턴" 정의

    시나리오별 차이:
      paper  : 좌→우 읽기(hc)가 집중의 핵심 → 높은 가중치
      coding : 에디터 고정(disp↓)이 핵심, 마우스 활발함도 집중 신호
      lecture: 화면 고정(disp↓, stability)이 핵심, video 비율 추가

    공통 제외 항목 (engagement와 중복 방지):
      - feat_section_score_mean  (섹션 콘텐츠 맥락)
      - feat_scroll_regularity   (콘텐츠 탐색 패턴)
      - feat_revisit_rate        (콘텐츠 재방문)
      - feat_fixation_duration   (fatigue와 중복)
      - feat_iris_movement       (실제 데이터에서 역방향 확인됨)
      - feat_saccade_velocity    (실제 데이터에서 역방향 확인됨)
    """
    disp = _normalize(df['feat_gaze_dispersion'])   # ↓ 집중
    back = _normalize(df['feat_backtrack_ratio'])   # ↓ 집중
    hc   = _normalize(df['feat_horizontal_consistency'])  # ↑ 집중 (paper 핵심)

    if scenario == 'paper':
        # 좌→우 선형 읽기가 논문 집중의 핵심
        gt = (
            0.50 * (1 - disp)   # 시선 집중 (에디터/화면 고정)
            + 0.30 * hc         # 좌→우 읽기 (논문 특화)
            + 0.20 * (1 - back) # 역방향 억제
        )

    elif scenario == 'coding':
        has_mouse = df['feat_mouse_speed_mean'].sum() > 0
        if has_mouse:
            ms = _normalize(df['feat_mouse_speed_mean'])  # ↑ 집중 (활발한 코딩)
            gt = (
                0.45 * (1 - disp)   # 에디터 집중
                + 0.30 * (1 - back) # 역참조 억제
                + 0.25 * ms         # 마우스 활발 (코딩 활동성)
            )
        else:
            gt = (
                0.50 * (1 - disp)
                + 0.30 * hc
                + 0.20 * (1 - back)
            )

    elif scenario == 'lecture':
        stab = _normalize(df['feat_gaze_stability'])  # ↑ 집중 (화면 고정)
        has_video = df['feat_video_watch_ratio'].sum() > 0
        if has_video:
            video = _normalize(df['feat_video_watch_ratio'])  # ↑ 집중
            gt = (
                0.40 * (1 - disp)   # 시선 집중
                + 0.35 * video      # 영상 주시 (강의 특화)
                + 0.25 * (1 - back) # 역방향 억제
            )
        else:
            gt = (
                0.50 * (1 - disp)
                + 0.30 * stab
                + 0.20 * (1 - back)
            )

    gt_arr     = gt.clip(0, 1).values
    before_std = gt_arr.std()
    gt_arr     = _sigmoid_normalize(gt_arr, scale=6.0)
    print(f'    GT: std {before_std:.4f} → {gt_arr.std():.4f}  '
          f'mean={gt_arr.mean():.4f}')
    return gt_arr


# ==============================================================================
# STEP 4. 전체 파이프라인
# ==============================================================================

def run_pipeline(subject: str, scenario: str,
                  input_path: str, output_path: str):
    print(f"\n{'='*60}")
    print(f"  {scenario.upper()} — {subject}")
    print(f"{'='*60}")

    if not os.path.exists(input_path):
        print(f"  ❌ 파일 없음: {input_path}")
        return

    df = pd.read_csv(input_path)
    print(f"  로드: {df.shape[0]}행 × {df.shape[1]}열")
    if 'gaze_section' in df.columns:
        print(f"  gaze_section:\n{df['gaze_section'].value_counts().to_string()}")

    # Feature
    print('\n  [1/3] Feature 추출...')
    df = extract_gaze_features(df, scenario=scenario, window_sec=3.0)

    # States
    print('  [2/3] Engagement / Confusion / Fatigue...')
    df['engagement'], df['confusion'], df['fatigue'] = compute_states(df, scenario)
    df = smooth_and_normalize(df, ['engagement','confusion','fatigue'], smooth_sec=2.0)
    df = discretize(df, ['engagement','confusion','fatigue'])

    # GT
    print('  [3/3] objective_gt (engagement 독립 신호)...')
    df['objective_gt'] = compute_objective_gt(df, scenario)
    df['objective_gt'] = df['objective_gt'].fillna(df['objective_gt'].median())

    # 시나리오 라벨
    scenario_code = {'paper': 0, 'lecture': 1, 'coding': 2}
    df['scenario']         = scenario_code[scenario]
    df['scenario_paper']   = int(scenario == 'paper')
    df['scenario_lecture'] = int(scenario == 'lecture')
    df['scenario_coding']  = int(scenario == 'coding')

    # 검증
    gt_vals = df['objective_gt'].values
    eng_vals = df['engagement'].values

    from scipy.stats import pearsonr
    from sklearn.metrics import r2_score
    corr_eng, _ = pearsonr(gt_vals, eng_vals)
    r2_eng      = r2_score(gt_vals, eng_vals)
    corr_con, _ = pearsonr(gt_vals, df['confusion'].values)

    print(f'\n  engagement ↔ GT: r={corr_eng:.4f}  R²={r2_eng:.4f}')
    print(f'  confusion  ↔ GT: r={corr_con:.4f}  (음수 정상)')

    # R² 0.9 이상이면 순환 정의 경고
    if r2_eng > 0.90:
        print('  ⚠️  R²>0.90: GT와 engagement가 거의 동일 → 순환 정의 위험')
    elif r2_eng > 0.5:
        print('  ✅ 적절한 상관 (GT ≠ engagement, 독립성 확보)')
    else:
        print('  ✅ GT가 engagement와 충분히 독립적')

    # GT 분포
    bins   = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
    labels = ['0~0.2','0.2~0.4','0.4~0.6','0.6~0.8','0.8~1.0']
    print('\n  GT 분포:')
    for i in range(len(bins)-1):
        cnt = ((gt_vals >= bins[i]) & (gt_vals < bins[i+1])).sum()
        pct = cnt / len(gt_vals) * 100
        bar = '█' * int(pct / 2)
        flag = ' ⚠️' if pct > 45 else ''
        print(f'  {labels[i]}: {bar} {pct:.1f}%{flag}')

    # 저장
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False, encoding='utf-8-sig')
    print(f'\n  ✅ 저장: {output_path}')


# ==============================================================================
# 실행
# ==============================================================================

os.makedirs(BASE_OUT, exist_ok=True)

for scenario, subjects in SUBJECT_FILES.items():
    for subject, input_path, output_path in subjects:
        run_pipeline(subject, scenario, input_path, output_path)

print('\n' + '='*60)
print('✅ 전체 완료')
print('='*60)
print('\nLOO-CV FILE_PATHS 순서:')
for scenario, subjects in SUBJECT_FILES.items():
    for subject, _, output_path in subjects:
        print(f'  {os.path.basename(output_path)}')

print("""
[다음 단계]
1. 위 파일들을 LOO-CV FILE_PATHS에 순서대로 입력
2. normalize_gt_within_scenario() 적용 (시나리오별 minmax)
3. LOO-CV 실행
4. 각 fold R² 확인:
   - engagement ↔ GT r이 0.5~0.8이면 이상적
   - r > 0.95이면 순환 정의 → sigmoid_scale 낮추기
   - r < 0.3이면 GT 방향 확인 필요
""")