# -*- coding: utf-8 -*-
"""train_loo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8EKufGBB0UnMAmfF206Xa-UBGJYUm2V

train_loo.py
Early Fusion BiLSTM 기반 몰입도 회귀 모델 학습.
Leave-One-Out Cross-Validation (참가자 단위) 적용.
Input : gaze(9) + MAUI(5) + scenario one-hot(3) = 17차원
Target: objective_gt (SAES)
"""

from google.colab import drive
drive.mount('/content/drive')

"""
bilstm_early_fusion_loo.py (v2)
--------------------------------
변경사항:
    1. 시나리오 원핫 feature 추가 (scenario_paper / scenario_coding / scenario_lecture)
       - 정규화 제외, 0/1 그대로 입력
    2. 타겟: engagement/confusion/fatigue → objective_gt (단일 회귀)
"""

import os, time, warnings
import numpy as np
import pandas as pd
import psutil
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

# ==============================================================================
# 1. CONFIG
# ==============================================================================
FILE_PATHS = [
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_coding_namwoo.csv",
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_coding_yoonjo.csv",
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_lecture_namwoo.csv",
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_lecture_yoonjo.csv",
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_paper_jisu.csv",
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_paper_namwoo.csv",
    "/content/drive/MyDrive/livinglab_2/data/gaze_output/자동라벨링결과/autogaze_paper_yoonjo.csv"
]
OUTPUT_DIR = "/content/drive/MyDrive/livinglab_2/cross_training/outputs"

# ── Feature 구성 ────────────────────────────────────────────────────────────
GAZE_FEATURE_COLS = [
    'feat_horizontal_consistency',
    'feat_backtrack_ratio',
    'feat_gaze_dispersion',
    'feat_saccade_velocity_mean',
    'feat_fixation_duration_mean',
    'feat_iris_movement',
    'feat_revisit_rate',
    'gaze_x',
    'gaze_y',
]
'''
MAUI_FEATURE_COLS = [
    'screen_x_px',
    'screen_y_px',
    'feat_section_score_mean',
    'feat_top_seg_score_mean',
    'feat_section_consistency',
]
'''
MAUI_FEATURE_COLS = []

# 시나리오 원핫 — 정규화 제외 대상
SCENARIO_COLS = [
    'scenario_paper',    # 논문 읽기
    'scenario_coding',   # 코딩
    'scenario_lecture',  # 온라인 강의
]

# 정규화할 feature (gaze + maui)
SCALE_COLS   = GAZE_FEATURE_COLS + MAUI_FEATURE_COLS
# 전체 입력 feature (정규화 feature + 시나리오 원핫)
FEATURE_COLS = SCALE_COLS + SCENARIO_COLS

# 타겟: objective_gt 단일 회귀
TARGET_COLS  = ['objective_gt']

SEED        = 42
SEQ_LEN     = 50
STRIDE      = 25
HIDDEN_SIZE = 128
NUM_LAYERS  = 2
DROPOUT     = 0.3
BATCH_SIZE  = 32
EPOCHS      = 50
LR          = 1e-3
PATIENCE    = 10

torch.manual_seed(SEED)
np.random.seed(SEED)
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


# ==============================================================================
# 2. 유틸
# ==============================================================================

def get_ram_mb():
    return psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2


@torch.no_grad()
def measure_infer_per_seq_ms(model, X_test, n_runs=10):
    model.eval()
    X_t = torch.tensor(X_test, dtype=torch.float32).to(DEVICE)
    _ = model(X_t[:1])
    if DEVICE.type == 'cuda':
        torch.cuda.synchronize()
    times = []
    for _ in range(n_runs):
        t0 = time.perf_counter()
        _ = model(X_t)
        if DEVICE.type == 'cuda':
            torch.cuda.synchronize()
        times.append((time.perf_counter() - t0) * 1000)
    return float(np.mean(times)) / len(X_t)


# ==============================================================================
# 3. 데이터 로딩
# ==============================================================================

def add_scenario_onehot(df: pd.DataFrame) -> pd.DataFrame:
    """
    scenario 컬럼(0=paper, 1=lecture, 2=coding)을 원핫으로 변환.
    scenario 컬럼이 없으면 모두 0으로 채움.
    """
    mapping = {0: 'paper', 1: 'lecture', 2: 'coding'}
    for col in SCENARIO_COLS:
        df[col] = 0.0

    if 'scenario' in df.columns:
        for code, name in mapping.items():
            mask = df['scenario'] == code
            df.loc[mask, f'scenario_{name}'] = 1.0
    else:
        # scenario 컬럼 없으면 파일명으로 추정
        print("  ⚠️  scenario 컬럼 없음 → 원핫 0으로 설정 (파일별 수동 확인 필요)")

    return df


def load_data(file_paths: list) -> list:
    dfs = []
    for path in file_paths:
        df = pd.read_csv(path).sort_values('timestamp_sec').reset_index(drop=True)

        # 시나리오 원핫 추가
        df = add_scenario_onehot(df)

        # 없는 feature 컬럼 0으로 채움
        for col in SCALE_COLS:
            if col not in df.columns:
                df[col] = 0.0
                print(f"  ⚠️  {col} 없음 → 0으로 채움")

        # objective_gt 없으면 에러
        if 'objective_gt' not in df.columns:
            raise ValueError(f"objective_gt 컬럼이 없습니다: {path}\n"
                             f"자동라벨링 코드에서 objective_gt를 먼저 생성해주세요.")

        df[SCALE_COLS]   = df[SCALE_COLS].ffill().fillna(0)
        df[TARGET_COLS]  = df[TARGET_COLS].ffill().fillna(0)

        # 시나리오 원핫 분포 확인
        scenario_counts = {col: int(df[col].sum()) for col in SCENARIO_COLS}
        print(f"  Loaded: {os.path.basename(path)}  |  {df.shape[0]}행  "
              f"|  시나리오 {scenario_counts}")
        dfs.append(df)
    return dfs


# ==============================================================================
# 4. 슬라이딩 윈도우 시퀀스 생성
# ==============================================================================

def make_sequences(df: pd.DataFrame, scaler: StandardScaler, fit: bool = False):
    """
    시나리오 원핫은 정규화 제외.
    X : (N, SEQ_LEN, len(SCALE_COLS) + len(SCENARIO_COLS))
    y : (N, 1)  objective_gt
    """
    X_scale = df[SCALE_COLS].values.astype(np.float32)
    X_scene = df[SCENARIO_COLS].values.astype(np.float32)   # 정규화 제외
    y_raw   = df[TARGET_COLS].values.astype(np.float32)

    if fit:
        X_scale = scaler.fit_transform(X_scale)
    else:
        X_scale = scaler.transform(X_scale)

    # 정규화된 feature + 시나리오 원핫 합치기
    X_raw = np.concatenate([X_scale, X_scene], axis=1)

    X_seqs, y_seqs = [], []
    for start in range(0, len(X_raw) - SEQ_LEN + 1, STRIDE):
        end = start + SEQ_LEN
        X_seqs.append(X_raw[start:end])
        y_seqs.append(y_raw[end - 1])

    return np.array(X_seqs), np.array(y_seqs)


# ==============================================================================
# 5. Dataset
# ==============================================================================

class GazeDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


# ==============================================================================
# 6. Early Fusion BiLSTM (단일 출력: objective_gt)
# ==============================================================================

class EarlyFusionBiLSTM(nn.Module):
    """
    입력: gaze(9) + MAUI(5) + 시나리오 원핫(3) = 17차원
    출력: objective_gt (1개, Sigmoid → 0~1)
    """
    def __init__(
        self,
        input_size:  int   = len(FEATURE_COLS),
        hidden_size: int   = HIDDEN_SIZE,
        num_layers:  int   = NUM_LAYERS,
        dropout:     float = DROPOUT,
        output_size: int   = len(TARGET_COLS),   # 1
    ):
        super().__init__()
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.norm = nn.LayerNorm(hidden_size * 2)
        self.head = nn.Sequential(
            nn.Linear(hidden_size * 2, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, output_size),
        )

    def forward(self, x):
        out, _ = self.bilstm(x)
        out    = self.norm(out[:, -1, :])
        return self.head(out)


# ==============================================================================
# 7. 학습 / 평가 함수
# ==============================================================================

def train_epoch(model, loader, optimizer, criterion):
    model.train()
    total_loss = 0
    for X_b, y_b in loader:
        X_b, y_b = X_b.to(DEVICE), y_b.to(DEVICE)
        optimizer.zero_grad()
        loss = criterion(model(X_b), y_b)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
        optimizer.step()
        total_loss += loss.item() * len(X_b)
    return total_loss / len(loader.dataset)


@torch.no_grad()
def eval_epoch(model, loader, criterion):
    model.eval()
    total_loss, preds, targets = 0.0, [], []
    for X_b, y_b in loader:
        X_b, y_b = X_b.to(DEVICE), y_b.to(DEVICE)
        p = model(X_b)
        total_loss += criterion(p, y_b).item() * len(X_b)
        preds.append(p.cpu().numpy())
        targets.append(y_b.cpu().numpy())
    return (
        total_loss / len(loader.dataset),
        np.concatenate(preds),
        np.concatenate(targets),
    )


# ==============================================================================
# 8. LOO-CV 메인 루프
# ==============================================================================

def run_loo_cv(dfs: list) -> pd.DataFrame:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"\n디바이스: {DEVICE}")
    print(f"입력 크기: scale({len(SCALE_COLS)}) + scenario({len(SCENARIO_COLS)}) = {len(FEATURE_COLS)}")
    print(f"타겟: objective_gt (단일 회귀)")
    print("=" * 65)

    loo_results      = []
    all_fold_preds   = {}
    all_fold_targets = {}

    for test_idx in range(len(dfs)):
        torch.manual_seed(SEED)
        np.random.seed(SEED)

        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(SEED)

        train_idxs = [i for i in range(len(dfs)) if i != test_idx]
        print(f"\n[Fold {test_idx+1}]  Test: {test_idx+1}  |  Train: {[i+1 for i in train_idxs]}")

        ram_before = get_ram_mb()

        # scaler: train 데이터의 scale_cols만 fit
        train_concat = pd.concat([dfs[i] for i in train_idxs], ignore_index=True)
        scaler = StandardScaler()
        scaler.fit(train_concat[SCALE_COLS].values)

        # 시퀀스 생성
        X_tr_list, y_tr_list = [], []
        for i in train_idxs:
            Xs, ys = make_sequences(dfs[i], scaler, fit=False)
            X_tr_list.append(Xs); y_tr_list.append(ys)
        X_train = np.concatenate(X_tr_list)
        y_train = np.concatenate(y_tr_list)
        X_test, y_test = make_sequences(dfs[test_idx], scaler, fit=False)

        print(f"  Train: {X_train.shape}  |  Test: {X_test.shape}")

        # Validation split
        X_tr, X_val, y_tr, y_val = train_test_split(
          X_train,
          y_train,
          test_size=0.15,
          random_state=SEED,
          shuffle=True
      )

        generator = torch.Generator()
        generator.manual_seed(SEED)

        train_loader = DataLoader(
            GazeDataset(X_tr, y_tr),
            batch_size=BATCH_SIZE,
            shuffle=True,
            generator=generator
        )
        val_loader   = DataLoader(GazeDataset(X_val, y_val), batch_size=BATCH_SIZE)
        test_loader  = DataLoader(GazeDataset(X_test, y_test), batch_size=BATCH_SIZE)

        # 모델 초기화
        model     = EarlyFusionBiLSTM().to(DEVICE)
        optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, factor=0.5)
        criterion = nn.MSELoss()

        # 학습
        best_val, best_state, no_improve = float('inf'), None, 0
        train_losses, val_losses = [], []
        train_start = time.perf_counter()

        for epoch in range(1, EPOCHS + 1):
            tr_loss = train_epoch(model, train_loader, optimizer, criterion)
            vl_loss, _, _ = eval_epoch(model, val_loader, criterion)
            scheduler.step(vl_loss)
            train_losses.append(tr_loss); val_losses.append(vl_loss)

            MIN_DELTA = 1e-4

            if best_val - vl_loss > MIN_DELTA:
                best_val   = vl_loss
                best_state = {k: v.clone() for k, v in model.state_dict().items()}
                no_improve = 0
            else:
                no_improve += 1

            if epoch % 10 == 0:
                print(f"  Epoch {epoch:3d} | train={tr_loss:.4f} | val={vl_loss:.4f} | lr={optimizer.param_groups[0]['lr']:.2e}")
            if no_improve >= PATIENCE:
                print(f"  Early stopping @ epoch {epoch}"); break

        train_time = time.perf_counter() - train_start

        # 테스트 평가
        model.load_state_dict(best_state)
        _, preds, targets = eval_epoch(model, test_loader, criterion)
        infer_ms  = measure_infer_per_seq_ms(model, X_test)
        ram_delta = get_ram_mb() - ram_before

        all_fold_preds[test_idx]   = preds
        all_fold_targets[test_idx] = targets

        # 메트릭
        mae  = mean_absolute_error(targets, preds)
        rmse = np.sqrt(mean_squared_error(targets, preds))
        r2   = r2_score(targets, preds)

        fold_metrics = {
            'fold':             test_idx + 1,
            'objective_gt_MAE': round(mae,  4),
            'objective_gt_RMSE':round(rmse, 4),
            'objective_gt_R2':  round(r2,   4),
            'train_time_sec':   round(train_time, 2),
            'infer_per_seq_ms': round(infer_ms, 5),
            'ram_delta_mb':     round(ram_delta, 1),
        }
        print(f"\n  ── 테스트 결과 (Fold {test_idx+1}) ──")
        print(f"  [objective_gt]  MAE={mae:.4f}  RMSE={rmse:.4f}  R²={r2:.4f}")
        print(f"  학습={train_time:.1f}s  |  추론/seq={infer_ms:.5f}ms  |  RAM Δ={ram_delta:+.1f}MB")
        loo_results.append(fold_metrics)

        # Loss 곡선
        fig, ax = plt.subplots(figsize=(7, 3))
        ax.plot(train_losses, color='#378ADD', lw=1.8, label='Train')
        ax.plot(val_losses,   color='#D85A30', lw=1.8, label='Val')
        ax.set_title(f'Fold {test_idx+1} — Loss Curve (objective_gt)')
        ax.set_xlabel('Epoch'); ax.set_ylabel('MSE Loss')
        ax.legend(); ax.grid(alpha=0.3)
        ax.spines[['top', 'right']].set_visible(False)
        plt.tight_layout()
        plt.savefig(os.path.join(OUTPUT_DIR, f'loss_fold{test_idx+1}.png'), dpi=120)
        plt.show()

    plot_all_folds(all_fold_preds, all_fold_targets)

    results_df = pd.DataFrame(loo_results)
    print(f"\n{'='*65}")
    print("LOO-CV 최종 결과 (objective_gt 단일 회귀)")
    print('='*65)
    print(results_df.to_string(index=False))
    print("\n[전체 평균]")
    print(results_df.drop(columns='fold').mean().to_string())

    results_df.to_csv(os.path.join(OUTPUT_DIR, 'loo_results_objective_gt.csv'), index=False)
    print(f"\n결과 저장: {OUTPUT_DIR}/loo_results_objective_gt.csv")
    return results_df


# ==============================================================================
# 9. 시각화
# ==============================================================================

def plot_all_folds(all_preds, all_targets):
    n_folds = len(all_preds)
    n_show  = 150
    COLOR   = '#378ADD'

    fig = plt.figure(figsize=(5 * n_folds, 4))
    fig.suptitle('Early Fusion BiLSTM — objective_gt 예측 vs 실제', fontsize=13)
    gs = gridspec.GridSpec(1, n_folds, hspace=0.4, wspace=0.3)

    for fold_i in range(n_folds):
        ax  = fig.add_subplot(gs[0, fold_i])
        tgt = all_targets[fold_i][:n_show, 0]
        pred= all_preds[fold_i][:n_show, 0]

        ax.plot(tgt,  color=COLOR, lw=1.5, alpha=0.9, label='실제')
        ax.plot(pred, color=COLOR, lw=1.2, alpha=0.6, linestyle='--', label='예측')

        mae = mean_absolute_error(all_targets[fold_i], all_preds[fold_i])
        r2  = r2_score(all_targets[fold_i], all_preds[fold_i])
        ax.set_title(f'Fold {fold_i+1}\nMAE={mae:.3f}  R²={r2:.3f}', fontsize=9)
        ax.set_ylim(-0.05, 1.05)
        ax.grid(alpha=0.3); ax.spines[['top', 'right']].set_visible(False)
        if fold_i == 0:
            ax.legend(fontsize=7, loc='upper right')

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'predictions_objective_gt.png'), dpi=120, bbox_inches='tight')
    plt.show()


# ==============================================================================
# 10. 실행
# ==============================================================================

print("데이터 로딩 중...")
dfs = load_data(FILE_PATHS)

print(f"\n입력 feature ({len(FEATURE_COLS)}개)")
print(f"  Scale  ({len(SCALE_COLS)}개): gaze {len(GAZE_FEATURE_COLS)}개 + MAUI {len(MAUI_FEATURE_COLS)}개")
print(f"  Scenario ({len(SCENARIO_COLS)}개): {SCENARIO_COLS}  ← 정규화 제외")
print(f"  타겟: {TARGET_COLS}")

# ==============================================================================
# 기존 bilstm_early_fusion_loo.py 에 추가할 내용
# ==============================================================================
#
# [추가 위치]
#   load_data() 호출 직후, run_loo_cv() 호출 직전
#
# [왜 이 위치인가]
#   - dfs 리스트가 완성된 후
#   - LOO-CV 루프 시작 전
#   → 정규화된 GT를 갖고 LOO-CV를 실행
#
# [기존 코드에서 바꿀 부분]
#   ❌ 기존:
#       print("데이터 로딩 중...")
#       dfs = load_data(FILE_PATHS)
#       ...
#       results = run_loo_cv(dfs)
#
#   ✅ 수정:
#       print("데이터 로딩 중...")
#       dfs = load_data(FILE_PATHS)
#       dfs = normalize_gt_within_scenario(dfs, FILE_PATHS)   # ← 이 줄 추가
#       ...
#       results = run_loo_cv(dfs)

# ==============================================================================
# 추가할 함수 — run_loo_cv() 정의 바로 위에 붙여넣으세요
# ==============================================================================

def normalize_gt_within_scenario(dfs: list, file_paths: list) -> list:
    """
    시나리오별 피험자 간 objective_gt minmax 정규화.

    [왜 필요한가]
      coding_namwoo와 coding_yoonjo의 GT 절대 스케일이 달라서
      yoonjo로 학습한 모델이 namwoo를 예측할 때 범위를 벗어남.
      → 시나리오 내 전체 GT를 0~1로 맞춰 스케일 통일.

    [시나리오 경계를 넘지 않는 이유]
      coding GT와 paper GT를 같이 정규화하면 시나리오 특성이 섞임.
      → coding끼리, paper끼리, lecture끼리 독립 정규화.

    [FILE_PATHS 에서 시나리오 자동 추출]
      파일명에 'coding' / 'paper' / 'lecture' 가 포함되어 있다고 가정.
      예: autogaze_labeled_coding_v4_namwoo.csv → 'coding'
    """
    import re

    # 파일명에서 시나리오 추출
    def extract_scenario(path: str) -> str:
        fname = os.path.basename(path).lower()
        if 'coding'  in fname: return 'coding'
        if 'lecture' in fname: return 'lecture'
        if 'paper'   in fname: return 'paper'
        return 'unknown'

    scenarios = [extract_scenario(p) for p in file_paths]

    # 시나리오별 인덱스 묶기
    scenario_groups = {}
    for idx, scen in enumerate(scenarios):
        scenario_groups.setdefault(scen, []).append(idx)

    print("\n" + "="*60)
    print("⚙️  시나리오별 GT 정규화")
    print("="*60)

    dfs_out = [df.copy() for df in dfs]

    for scen, indices in scenario_groups.items():
        # 시나리오 내 전체 GT 수집
        all_gt = np.concatenate([dfs[i]['objective_gt'].values for i in indices])
        gt_min, gt_max = all_gt.min(), all_gt.max()

        print(f"\n  [{scen}] 피험자 {len(indices)}명")
        print(f"    정규화 전: mean={all_gt.mean():.3f}  std={all_gt.std():.3f}  "
              f"range=[{gt_min:.3f}, {gt_max:.3f}]")

        if gt_max - gt_min < 1e-6:
            print(f"    ⚠️  GT 범위가 너무 좁음 → 정규화 스킵")
            continue

        # 각 파일의 GT를 시나리오 내 전체 범위로 정규화
        for i in indices:
            fname = os.path.basename(file_paths[i])
            gt_before = dfs_out[i]['objective_gt'].values.copy()
            gt_normed = np.clip((gt_before - gt_min) / (gt_max - gt_min), 0, 1)
            dfs_out[i]['objective_gt'] = gt_normed

            print(f"    {fname}")
            print(f"      before: mean={gt_before.mean():.3f}  std={gt_before.std():.3f}")
            print(f"      after:  mean={gt_normed.mean():.3f}  std={gt_normed.std():.3f}")

        # 정규화 후 시나리오 전체 통계
        all_gt_after = np.concatenate([dfs_out[i]['objective_gt'].values for i in indices])
        print(f"    정규화 후: mean={all_gt_after.mean():.3f}  std={all_gt_after.std():.3f}  "
              f"range=[{all_gt_after.min():.3f}, {all_gt_after.max():.3f}]")

    print("\n✅ GT 정규화 완료\n")
    return dfs_out


# ==============================================================================
# 실행부 수정 — 기존 코드 맨 아래를 아래처럼 교체
# ==============================================================================

print("데이터 로딩 중...")
dfs = load_data(FILE_PATHS)

# ↓↓↓ 이 한 줄 추가 ↓↓↓
dfs = normalize_gt_within_scenario(dfs, FILE_PATHS)
# ↑↑↑ 여기까지 ↑↑↑

print(f"\n입력 feature ({len(FEATURE_COLS)}개)")
print(f"  Scale  ({len(SCALE_COLS)}개): gaze {len(GAZE_FEATURE_COLS)}개 + MAUI {len(MAUI_FEATURE_COLS)}개")
print(f"  Scenario ({len(SCENARIO_COLS)}개): {SCENARIO_COLS}  ← 정규화 제외")
print(f"  타겟: {TARGET_COLS}")

print("\nLOO Cross-Validation 시작...")
results = run_loo_cv(dfs)